### ISSUE TITLE
CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin is not set

### ISSUE THREAD

**Issue by ghost** [quintus-lab/NanoPi-R4S-OpenWRT#2]
Hi，the plugin CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin is the 2rd verison for shadowsocks-libev plugin，relay TLS,could you set by
 default?

**Comment by quintus-lab** [comment]
I think it's a stupid idea for SS to have a plugin that's much bigger than it is, so it won't be added, and it will cause some compilation issues
