### ISSUE TITLE
VLAN support?

### ISSUE THREAD

**Issue by ghost** [quintus-lab/NanoPi-R4S-OpenWRT#3]
Hi, I flashed the Quintus Build@2021.01.07 firmware, but I didn't see that Luci has vlan support. What did I do wrong?

**Comment by quintus-lab** [comment]
What type VLAN support did you mean?
There is no VLAN-capable hardware switch integrated in R4S router.
In case of extending the R4S ports with a managed switch with VLANs, you can create a new sub-interface  in LuCI for VLAN x,  Network -> Interfaces -> Add new interface ->

![](https://forum.openwrt.org/uploads/default/original/2X/4/4b23be9ecb72bf0187a485829f8b88d2c6b218e3.png)

**Comment by ghost** [comment]
I need to integrate the iptv of udp stream into lan, Internet VLAN ID tag, IPTV VLAN ID untag, what can I do?

**Comment by quintus-lab** [comment]
create one sub-interface on eth0(WAN) for IPTV, such as eth0.20 ( vlan 20 for iptv)

**Comment by ghost** [comment]
Great!thanks a lot.
